name: project-lifecycle
on:
  schedule:
    - cron: 0 7 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled

permissions: {}

jobs:
  lifecycle:
    uses: kumahq/.github/.github/workflows/wfc_lifecycle.yml@9e5f50367a10d2a24ec254bdeac03b5f40bde55c
    secrets:
      app_id: ${{ vars.KONG_MESH_APP_ID }}
      private_key: ${{ secrets.KONG_MESH_APP_PRIVATE_KEY }}
    permissions:
      actions: read
      contents: write
      issues: write
      pull-requests: write
    with:
      filesToIgnore: "CODE_OF_CONDUCT.md,LICENSE,SECURITY.md,CODEOWNERS,GOVERNANCE.md,CONTRIBUTING.md"
