name: project-lifecycle
on:
  schedule:
    - cron: 0 7 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled

permissions: {}

jobs:
  lifecycle:
    uses: kumahq/.github/.github/workflows/wfc_lifecycle.yml@2e670e4083642dfa8f047fab84c6436d28ef81a4
    permissions:
      actions: read
      contents: write
      issues: write
      pull-requests: write
    with:
      filesToIgnore: "CODE_OF_CONDUCT.md,LICENSE,SECURITY.md,CODEOWNERS,GOVERNANCE.md,CONTRIBUTING.md"
